posts/urls.py
from django.urls import path, include
from . import views

app_name = "posts"

urlpatterns = [
    path("posts", views.list, name="list"),
    path("posts/<int:id>", views.details, name="details")
]

posts_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls"))
]

posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

posts/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render
from .services import PostService, PostNotFound


# Create your views here.
def list(request) -> HttpResponse:

    if request.method == 'POST':
        PostService.create(
            title=request.POST.get("post_title"),
            content=request.POST.get("post_content")
        )

    results = PostService.list()
    return render(
        request=request,
        template_name="posts.html",
        context={"list_of_posts": results}
    )

def details(request, id: int) -> HttpResponse:
    try:
        result = PostService.get(id)
    except PostNotFound:
        raise Http404("Post nie istnieje")

    return render(
        request=request,
        template_name="posts_details.html",
        context={"post": result}
    )

posts/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>List of posts</title>
</head>
<body>
<h2>List of posts</h2>

<div>
{%  for p in list_of_posts %}
<p><a href="{% url 'posts:details' p.id%}">{{ p.title }}</a></p>
<p>(utworzono: {{ p.created_at }})</p>
<p>{{ p.content }}</p>
{%  endfor %}</div>

<div>
    <form method="post">
        {% csrf_token %}
        <p>
        <label for="p_title">Title</label>
        <input type="text" id="p_title" name="post_title">
        </p>
        <p>
        <label for="p_content">Content</label>
        <input type="text" id="p_content" name="post_content">
        </p>
        <p>
        <input type="submit" value="Send">
        </p>
    </form>
</div>

</body>
</html>

posts/templates/posts_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post details</title>
</head>
<body>
<h2>Post details</h2>

<div>
<p>{{ post.title }}</p>
<p>(utworzono: {{ post.created_at }})</p>
<p>{{ post.content }}</p>
</div>

</body>
</html>